---
## For full and default variables
## See roles/external/ansible-nginx/defaults/main.yml
## See https://www.nginx.com/resources/admin-guide/compression-and-decompression/

# Enables gzip compression for assets files
nginx_http_params :
                    gzip_comp_level : "6"
                    gzip_min_length : "1100"
                    gzip_buffers    : "16 8k"
                    gzip_proxied    : "any"
                    gzip_types      : "text/plain text/css text/js text/xml text/javascript application/javascript application/x-javascript application/json application/xml application/xml+rss"

nginx_site                          :
  - file_name                       : "wp-app"
    blocks                          :
       - type                       : "server"
         client_max_body_size       : "100M"
         listen                     : "80"
         server_name                : "kornienko.site {{ inventory_hostname }}"
         root                       : "{{ deployment_dir_current }}/"
         index                      : "index.php index.html index.htm"
         access_log                 : '/var/log/nginx/access-{{ inventory_hostname }}.log'
         error_log                  : '/var/log/nginx/error-{{ inventory_hostname }}.log'
         add_header                 : "X-Backend-Server $hostname"

       # ssl_certificate            : "/etc/ssl/certs/server.crt"
       # ssl_certificate_key        : "/etc/ssl/private/server.key"
       # try to serve file directly, fallback to index.php
         location0                   :
            type                     : "location"
            name                     : "/"
            try_files                : "$uri /index.php$is_args$args"

        # PROD
         location1                  :
            type                    : "location"
            name                    : "~ \\.php$"
            fastcgi_pass            : "127.0.0.1:9000"
            fastcgi_split_path_info : "^(.+\\.php)(/.*)$"
            include                 :
                                      - "/etc/nginx/fastcgi_params"
                                      - "{{ deployment_dir_base }}/current/fastcgi_env_vars"
            fastcgi_param           :
                                      - "SCRIPT_FILENAME $realpath_root$fastcgi_script_name"
                                      - "DOCUMENT_ROOT $realpath_root"